# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLwqQpNjW48Wx3SFyAPao0dcPToHwrwi
"""



"""Aquí hay un ejemplo de cómo podrías representar la información de un álbum usando un diccionario en Python:"""

# Crear un diccionario para un álbum
album_ejemplo = {
    "Artist": "Michael Jackson",
    "Album": "Thriller",
    "Released_year": 1982,
    "Length_min_sec": "00:42:19",
    "Genere": "Pop, rock, R&B",
    "Music_recording_sales_millions": 46.0,
    "Claimed_sales_millions": 65.0,
    "Released": "November 30, 1982",
    "Soundtrack": "N",
    "Rating_of_friends": 10
}

# Mostrar el diccionario completo
print("Información del álbum:")
print(album_ejemplo)

# Acceder a información
nombre_artista = album_ejemplo["Artist"]
año_lanzamiento = album_ejemplo["Released_year"]
genero = album_ejemplo["Genere"]

print(f"\nArtista: {nombre_artista}")
print(f"Año de lanzamiento: {año_lanzamiento}")
print(f"Género: {genero}")