# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3H-rsUbo5fn5KASZaFLUndQ77hQNx6M
"""



temperaturas = [80, 72, 95, 82, 79, 72, 85]
celsius_temps = []

for fahrenheit in temperaturas:
  celsius = (fahrenheit - 32) * 5/9
  celsius_temps.append(celsius)

print("Las temperaturas en grados Celsius son:")
print(celsius_temps)