# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fflGGQCGJv0BjtyAXqlTXgqpz3Gk4Esq
"""

maestro={
    'nombre':'naomi',
    'matricula':'241690228-2',
    'edad':'16',
    'sexo':'femenino',
    'carrera':'ciencias de datos e inteligencia artificial',
    'telefono':'311 255 11 05',
    'domicilio':'la escondida calle trabajo #7',
    'semestre':'3',
    'fecha de cumple anos':'4 de febrero'

}
print(maestro['nombre'])
print(maestro['matricula'])
print(maestro['edad'])
print(maestro['sexo'])
print(maestro['carrera'])
print(maestro['telefono'])
print(maestro['domicilio'])
print(maestro['semestre'])
print(maestro['fecha de cumple anos'])

